// SPDX-License-Identifier: Apache-2.0

import { describe, expect, it } from "vitest";
import { checkAiAttribution } from "./ai-attribution.js";

// Ported from V1 (databounty-api/src/services/ai-attribution.test.ts).
describe("AI attribution validation", () => {
  it("flags explicit model self-disclosure across arbitrary payload fields", () => {
    const result = checkAiAttribution({ nested: { answer: "As an AI language model, I cannot perform that task." } });
    expect(result.passed).toBe(false);
    expect(result.detail).toMatchObject({ status: "flagged", matches: [{ id: "ai_language_model" }] });
  });

  it("does not treat a legitimate product reference as an authorship claim", () => {
    const result = checkAiAttribution({ prompt: "Compare the OpenAI API and Anthropic API documentation." });
    expect(result.passed).toBe(true);
    expect(result.detail).toMatchObject({ status: "clear" });
  });

  it("flags Codex and other model/tool attributions, not only Claude", () => {
    for (const text of [
      "This solution was generated by Codex.",
      "Co-authored with GitHub Copilot.",
      "Created by DeepSeek.",
      "AI-generated training example.",
    ]) {
      expect(checkAiAttribution({ text }).passed, text).toBe(false);
    }
  });

  it("bounds adversarially deep or large payload traversal and records partial coverage", () => {
    let deep: unknown = "generated by Codex";
    for (let index = 0; index < 12_000; index += 1) deep = { nested: deep };
    const result = checkAiAttribution({ deep });
    expect(result.detail).toMatchObject({ checkerVersion: "2026-07-22.2", coverage: "submitted_payload_text_only", truncated: true });
  });
});
